### ISSUE TITLE
Could not find Praat

### ISSUE THREAD

**Issue by pr-crypto** [MLSpeech/Dr.VOT#1]
After ./check_installations.sh following error occurs:

> File "./helpers/check_req.py", line 9
> f"Couldn't Find Praat at : '/Applications/Praat.app/Contents/MacOS/Praat'"
> 
> SyntaxError: invalid syntax
> Missing requirements

Interestingly both MacOS Catalina and Ubuntu 16.04 throws exactly the same error.

Cheers

**Comment by yosishrem** [comment]
Hey, thanks for the feedback.
We support Python 3.6+, I will add it to the documentation.
Let me know if it doesn't fix it.

**Comment by pr-crypto** [comment]
Thanks for the response. Will update and let you know.

**Comment by pr-crypto** [comment]
Not much change after using python 3.7.5 as default:

`XXXXXX-MacBook-Pro-10:~ XXX$ python
Python 3.7.5 (default, Nov  1 2019, 02:16:23) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
XXXXXX-MacBook-Pro-10:~ USERNAME$ cd Dr.VOT
XXXXXX-MacBook-Pro-10:$Dr.VOT USERNAME$ ./check_installations.sh
  File "./helpers/check_req.py", line 9
    f"Couldn't Find praat at : '/Applications/Praat.app/Contents/MacOS/Praat'"
                                                                    
SyntaxError: invalid syntax
Missing requirements
`

**Comment by yosishrem** [comment]
Hey, I changed the check_installation script, can you please try to re-clone/pull the changes, and then:
$ pipenv --rm 2> /dev/null
$./check_installations.sh

**Comment by pr-crypto** [comment]
It seems like line no. 9 is now resolved and the problem moved to line 17 on Mac.
On the other hand, someone informs me that Linux is faring better. 
 

`USERNAME-MacBook-Pro-10:Dr.VOT USERNAME$ ./check_installations.sh`
  `File "./helpers/check_req.py", line 17`
    `raise SystemExit(f"Couldn't find Praat at :{os.path.join(os.getcwd(), 'linux_praat')}")`
                                                                                         ^
`SyntaxError: invalid syntax`
`Missing requirements`

**Comment by pr-crypto** [comment]
I think the problem is the "f" before the error messages. When deleted the "f" as below, thescript runs fine
`raise SystemExit(f"Couldn't find Praat at :{os.path.join(os.getcwd(), 'linux_praat')}")`
changed to
`raise SystemExit("Couldn't find Praat at :{os.path.join(os.getcwd(), 'linux_praat')}")`

**Comment by yosishrem** [comment]
Thanks for the feedback, I uploaded a slightly different version of this line.

**Comment by pr-crypto** [comment]
1. Sorry to be a pain. It seems like the "f" needs to be removed on lines 22, 26 and 29 also. 

2. I am also having trouble running python 3.7 by default but that has nothing to do with your code- just a public FYI.

**Comment by yosishrem** [comment]
The 'f' at the beginning is a pythonic way to format strings.it is supported from python 3.6+.
that's probably why you are having these errors.
try to pull the code and then:
1. edit a file names 'Pipfile' : remove the '#' at the last line
2. type 'pipenv shell'
Then, you are in a virtual environment mode that enforces python3.7. It should hopefully run without errors.
