### ISSUE TITLE
Some Questions Related to the Results

### ISSUE THREAD

**Issue by WangYao-GoGoGo** [MLSpeech/Dr.VOT#4]
Excuse me, I run your model and get the results file.
[xxxxx.TextGrid]
I don't know what is the meaning of "window" in the item[1].

item[1] -> intervals[2] -> text = "window" 

Thank you very much.

**Comment by yosishrem** [comment]
Hey, the "window" item shows the search window in which the system looks for the VOT's onset and offset. The VOT measurement is computationally exhaustive, so we narrow the search window to 250msec(extracted automatically) rather than the entire wav.

**Comment by WangYao-GoGoGo** [comment]
thank you very much
